name: Lifestyle Advisor Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create SSH directory
      run: mkdir -p ~/.ssh

    - name: Install SSH key
      run: |
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        if [ -f "red123.pem" ]; then chmod 600 "red123.pem"; fi

    - name: Update code on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          cd lifestyle-advisor/healthguide
          sudo su
          git stash
          git pull origin main
  
    - name: Stop running Python processes
      run: |
        pkill -f "python3" || true

    - name: Run the application
      run: |
        echo "OPENAI_SECRET_KEY=${{ secrets.OPENAI_SECRET_KEY }}" >> $GITHUB_ENV
        echo "AWS_COGNITO_DOMAIN=${{ secrets.AWS_COGNITO_DOMAIN }}" >> $GITHUB_ENV
        echo "AWS_COGNITO_USER_POOL_ID=${{ secrets.AWS_COGNITO_USER_POOL_ID }}" >> $GITHUB_ENV
        echo "AWS_COGNITO_USER_POOL_CLIENT_ID=${{ secrets.AWS_COGNITO_USER_POOL_CLIENT_ID }}" >> $GITHUB_ENV
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
        echo "AWS_COGNITO_USER_POOL_CLIENT_SECRET=${{ secrets.AWS_COGNITO_USER_POOL_CLIENT_SECRET }}" >> $GITHUB_ENV
